import random

# Shown when pace is BELOW (underusing) - wisdom about restraint and patience.
BELOW_QUOTES = [
    ("A wise man drives subagents; a fool develops inline.", "Plato"),
    ("He who compacts his context before it compacts him needs no reset.", "Sun Tzu"),
    ("The unexamined token is not worth spending.", "Socrates"),
    ("Patience is bitter, but its fruit is a fresh five-hour window.", "Aristotle"),
    ("He who forks wisely need never force-push in anger.", "Confucius"),
    ("The master delegates to the subagent and claims the credit; this too is virtue.", "Lao Tzu"),
    ("Know thyself, and thy context window.", "Socrates"),
    ("A single well-placed hook is worth a thousand manual checks.", "Marcus Aurelius"),
    ("The frugal engineer writes one commit for one thought.", "Seneca"),
    ("To cache is human; to recompute, folly.", "Epictetus"),
    ("He who reads the plan before acting wastes no tokens undoing.", "Confucius"),
    ("Small tasks, done in order, outlast grand designs abandoned at forty percent context.", "Marcus Aurelius"),
    ("The barrel that is never overfilled never spills.", "Diogenes"),
    ("I think, therefore I do not need three parallel agents to think for me.", "Descartes"),
    ("He who waits for the plan mode gate builds on rock, not sand.", "Aristotle"),
    ("The river that flows steadily reaches the sea; the one that floods reaches only ruin.", "Heraclitus"),
    ("Moderation in all things, even in the summoning of Opus.", "Aristotle"),
    ("A man who tests before he ships needs no apology after.", "Seneca"),
    ("The wise haiku model does more with less; be like the haiku model.", "Lao Tzu"),
    ("He who reads the diff before committing sees his own folly first.", "Socrates"),
    ("Virtue lies in the middle path between no agents and twenty agents.", "Aristotle"),
    ("The still mind writes the shorter prompt.", "Zhuangzi"),
    ("He who prunes his history file keeps his garden and his graph.", "Voltaire"),
    ("Better one skill invoked well than ten tools invoked poorly.", "Confucius"),
    ("The five-hour window is long to him who does not squander it before lunch.", "Seneca"),
    ("To automate wisely is to labor once and rest four times.", "Epictetus"),
    ("He who reads the error message first debugs twice as fast.", "Marcus Aurelius"),
    ("The disciplined mind schedules its wakeups; the anxious mind polls forever.", "Epictetus"),
    ("A tool used once and put away outlives a tool left running unwatched.", "Diogenes"),
    ("The wise do not mistake motion for progress, nor tokens for thought.", "Lao Tzu"),
]

# Shown when pace is AT (matching elapsed time) - wisdom about balance and the middle way.
AT_QUOTES = [
    ("He who matches his pace to the reset walks neither hungry nor stuffed.", "Aristotle"),
    ("The middle way spawns neither zero agents nor twenty; it spawns exactly as many as the task requires.", "Buddha"),
    ("To flow like water is to use exactly the tokens the task demands, no more, no less.", "Lao Tzu"),
    ("Virtue is a steady context window, neither starved nor bloated.", "Aristotle"),
    ("He who paces himself to the five-hour window arrives at the reset neither breathless nor bored.", "Marcus Aurelius"),
    ("The wise engineer commits neither too often nor too rarely, but exactly when the work is done.", "Confucius"),
    ("Balance is choosing Sonnet when Sonnet suffices and Opus when it does not.", "Epictetus"),
    ("He who neither hoards tokens nor squanders them has found the way.", "Lao Tzu"),
    ("The river that matches its banks neither floods nor runs dry.", "Heraclitus"),
    ("Equanimity is watching the pace bar and feeling nothing but mild satisfaction.", "Marcus Aurelius"),
    ("The archer who draws exactly enough strikes the mark; more or less, he misses.", "Zhuangzi"),
    ("He who reads one file before editing it, and no more, has mastered the mean.", "Confucius"),
    ("Steady hands write steady commits.", "Seneca"),
    ("The middle path forks one subagent for one hard problem, not one for every problem.", "Buddha"),
    ("He who neither underthinks nor overthinks the reasoning effort has found the tao of tool use.", "Lao Tzu"),
    ("Moderation is the rarest of the virtues, and the easiest to mistake for laziness.", "Aristotle"),
    ("The wise man watches his usage bar rise with his elapsed time, in step, like dancers.", "Plato"),
    ("To match effort to terrain is the general's whole art; to match tokens to task is the engineer's.", "Sun Tzu"),
    ("He who neither rushes the plan nor stalls in it moves at the only speed that matters.", "Epictetus"),
    ("The candle that burns steadily lights the whole night; the one that flares burns an hour.", "Seneca"),
    ("Neither the ascetic who runs no agents nor the glutton who runs fifty finds the way; the middle way runs exactly enough.", "Buddha"),
    ("He who checks his pace once an hour, not once a minute, has found peace.", "Epictetus"),
    ("The sage's context window is neither empty from disuse nor bursting from neglect.", "Zhuangzi"),
    ("Harmony is the sound of a five-hour window closing exactly as the work closes with it.", "Confucius"),
    ("He who commits at the natural breakpoints of his work needs no rhythm imposed from without.", "Marcus Aurelius"),
    ("The strategist who paces his reserves survives the whole campaign, not just the first battle.", "Sun Tzu"),
    ("Balance is not caution; it is knowing precisely how much caution the moment requires.", "Aristotle"),
    ("He who neither idles nor floods the terminal has made peace with the machine.", "Lao Tzu"),
    ("The mean between the miser and the spendthrift is not half of both; it is knowing the task.", "Aristotle"),
    ("To walk beside the clock, matching it step for step, is the quiet joy of the disciplined mind.", "Marcus Aurelius"),
]

# Shown when pace is ABOVE (overusing) - mockery of excess and wastefulness.
ABOVE_QUOTES = [
    ("He who forks ten agents to write one commit message has not saved time, only borrowed shame from the future.", "Nietzsche"),
    ("Man's greatest hubris is not fire, but setting reasoning effort to max for a spelling fix.", "Nietzsche"),
    ("He who summons Opus to summarize a haiku has lost the plot entirely.", "Kafka"),
    ("The abyss stares back, mostly to ask why you opened forty parallel tabs.", "Nietzsche"),
    ("There is no context window deep enough for a man who refuses to compact.", "Kafka"),
    ("He who spawns a subagent to spawn a subagent has built not a tool, but a bureaucracy.", "Kafka"),
    ("God is dead, and so is your five-hour window, by eleven in the morning.", "Nietzsche"),
    ("The absurd man reads no docs and re-derives the wheel, hourly.", "Camus"),
    ("One does not simply request medium effort when max is available; this is the tragedy of man.", "Sophocles"),
    ("The overconfident engineer forks first and reads the diff never.", "Machiavelli"),
    ("To rate-limit a man is to reveal what he truly worshipped: his own throughput.", "Nietzsche"),
    ("There is no sin greater than re-reading a file you just wrote, out of anxiety.", "Kafka"),
    ("He who requests the highest reasoning effort for hello world insults both the machine and himself.", "Diogenes"),
    ("The trial has no end, and neither does your context, for you never once compacted it.", "Kafka"),
    ("Ambition is calling twelve tools when one grep would have sufficed.", "Machiavelli"),
    ("He who polls every second has mistaken anxiety for diligence.", "Epicurus"),
    ("He who builds twelve microservices for a to-do list has confused architecture with anxiety.", "Machiavelli"),
    ("The will to power is, in the end, just wanting Opus for everything.", "Nietzsche"),
    ("He who never lets his agent rest burns twice as bright and finishes the window by noon.", "Heraclitus"),
    ("Absurdity is asking why the rate limit exists while triggering it for the fifth time this hour.", "Camus"),
    ("He who mistakes verbosity for thoroughness will exhaust the well before noon.", "Schopenhauer"),
    ("Hell is other agents' context, all crammed into yours.", "Sartre"),
    ("Whereof one cannot summarize, thereof one must keep prompting anyway.", "Wittgenstein"),
    ("The state of nature is nasty, brutish, and short, much like your remaining five-hour budget.", "Hobbes"),
    ("Man is born free, and everywhere he is in rate-limit chains of his own making.", "Rousseau"),
    ("The owl of Minerva spreads its wings only at dusk, long after you should have stopped forking agents.", "Hegel"),
    ("He who cannot explain his own workflow to himself has automated only his confusion.", "Wittgenstein"),
    ("Give a man a hammer and every problem becomes a twenty-agent orchestration.", "Nietzsche"),
    ("The examined life includes examining why you have six background tasks running at once.", "Socrates"),
    ("He who greedily hoards tokens for later finds later never comes, only the reset.", "Diogenes"),
]


def pick_quote(pool):
    return random.choice(pool)
