"""The thin index: the entire always-loaded footprint of the brain.

Two halves of the brain, two very different costs:

  RULES cost ZERO context. They are enforced by hooks, so the agent never needs to
  know they exist. Listing them would be pure waste, so the index gives a count and
  nothing more.

  NOTES cost one line each: their path and a one-line summary. The agent reads the
  full note only when it is about to touch that area.

The result is that a 3,000-token brain costs ~200 tokens at rest. Compare with the
usual approach - a 200-line AGENTS.md loaded in full, every session, and obeyed
inconsistently.

Regenerated by the distiller. Never hand-maintained.
"""

from __future__ import annotations

from pathlib import Path

from hookkit.frontmatter import parse

# Notes live in these folders. Everything else under .brain/ is machinery.
NOTE_DIRS = ("gotchas", "map", "utils", "notes")

MAX_SUMMARY = 68
MAX_NOTES = 40


def _summarise(path: Path) -> str:
    try:
        text = path.read_text()
    except OSError:
        return ""

    meta, body = parse(text)
    summary = meta.get("summary")
    if isinstance(summary, str) and summary.strip():
        return summary.strip()[:MAX_SUMMARY]

    for line in body.splitlines():
        line = line.strip()
        if line.startswith("#"):
            return line.lstrip("#").strip()[:MAX_SUMMARY]
        if line:
            return line[:MAX_SUMMARY]
    return ""


def generate(brain) -> str:
    """Build the index, write it to .brain/index.md, and return it."""
    root = Path(brain)

    entries = []
    for folder in NOTE_DIRS:
        directory = root / folder
        if not directory.is_dir():
            continue
        for path in sorted(directory.glob("*.md")):
            entries.append(("%s/%s" % (folder, path.stem), _summarise(path)))

    dropped = max(0, len(entries) - MAX_NOTES)
    entries = entries[:MAX_NOTES]

    rules_dir = root / "rules"
    rule_count = len(list(rules_dir.glob("*.md"))) if rules_dir.is_dir() else 0

    lines = ["## Project brain", ""]

    if entries:
        width = max(len(name) for name, _ in entries)
        lines.append("Read a note before working in the area it covers.")
        lines.append("")
        for name, summary in entries:
            lines.append("  %s  %s" % (name.ljust(width), summary) if summary else "  " + name)
        if dropped:
            lines.append("  ... and %d more (see .brain/)" % dropped)
        lines.append("")

    if rule_count:
        lines.append(
            "%d rule%s ACTIVE, enforced by hooks. You do not need to read them: if you "
            "are about to break one, you will be told at the moment it matters."
            % (rule_count, "" if rule_count == 1 else "s")
        )
    else:
        lines.append("No rules yet.")

    text = "\n".join(lines) + "\n"

    try:
        root.mkdir(parents=True, exist_ok=True)
        (root / "index.md").write_text(text)
    except OSError:
        pass

    return text
